import { Plugin } from '@sixsrc/brick-slider/api';
import { BSStoriesPluginOptions } from './types';
export declare class BrickSliderStories extends Plugin {
    private activeAnimation;
    private activeStoryIndex;
    private closeButton;
    private controlCleanupCallbacks;
    private isOpen;
    private isPaused;
    private isStoryHovered;
    private isTouchHoldingStory;
    private lastControlPointerTime;
    private muteButton;
    private pauseIndicator;
    private storiesLayer;
    private createdElements;
    private progressBars;
    private progressCleanupCallbacks;
    private progressContainer;
    private readonly pluginOptions;
    private hostMethods;
    private isDraggingStory;
    private storyPointerStartX;
    private storyTouchStartX;
    private storyTimer;
    private timerState;
    private triggerCleanupCallbacks;
    private warnedMultipleVideoStories;
    private lastTriggerElement;
    private mediaCleanupCallbacks;
    private mobileControlsTimer;
    private readonly hiddenBackgroundElements;
    private shouldResumeAfterTouchHold;
    private isTouchControlsVisible;
    private readonly handleSlideChange;
    private readonly handleCloseClick;
    private readonly handleMuteClick;
    private readonly handlePauseClick;
    private readonly handleWindowControl;
    private readonly handleWindowMouseMove;
    private readonly handleKeydown;
    private readonly handleMouseEnter;
    private readonly handleMouseMove;
    private readonly handleStoryPointerDown;
    private readonly handleStoryPointerUp;
    private showPauseControl;
    private readonly handleMouseLeave;
    private syncPauseHoverFromPointer;
    constructor(options?: BSStoriesPluginOptions);
    constructor($root: string, options?: BSStoriesPluginOptions);
    setHost(host: NonNullable<typeof this.host>): void;
    init(): void;
    private applyStoriesHostState;
    private validateMarkup;
    destroy(): void;
    open(): void;
    close(): void;
    pause(): void;
    resume(): void;
    private emitStoriesMountedWhenReady;
    private emitStoriesLifecycle;
    private focusInitialControl;
    private restoreTriggerFocus;
    private trapFocus;
    private getFocusableElements;
    private hideBackgroundFromAssistiveTech;
    private restoreBackgroundForAssistiveTech;
    private getBackgroundSiblings;
    private setupStoriesRoot;
    private setupStoriesLayer;
    private createStoriesLayer;
    private showStoriesLayer;
    private hideStoriesLayer;
    private setupProgress;
    private mountProgressBars;
    private bindProgressItem;
    private setupEdgeSwipeLock;
    private readonly handleStoryMouseDown;
    private readonly handleStoryMouseMove;
    private readonly handleStoryTouchStart;
    private readonly handleStoryTouchMove;
    private readonly handleStoryPointerEnd;
    private resumeStoryAfterPointerEnd;
    private startStoryDrag;
    private pauseStoryClock;
    private resumeStoryClock;
    private shouldLockEdgeSwipe;
    private isStoryControlTarget;
    private setupControls;
    private bindCloseControlEvents;
    private bindClickControlEvents;
    private isPrimaryControlEvent;
    private bindTrackHoverEvents;
    private mountStoriesElement;
    private setupTriggers;
    private bindTrigger;
    private wrapHostNavigation;
    private restoreHostNavigation;
    private getAdjacentStoryIndex;
    private syncHostNavigation;
    private syncStory;
    private syncProgressState;
    private syncProgressBar;
    private resetProgressItemState;
    private setActiveProgressItem;
    private setCompletedProgressItem;
    private animateProgress;
    private startTimer;
    private goToNextStory;
    private goToStory;
    private getCurrentStoryIndex;
    private getStoryIndexFromPayload;
    private getCurrentStoryDuration;
    private syncVideoState;
    private syncMediaControls;
    private syncMuteControl;
    private syncMuteDisabledState;
    private hideMediaControls;
    private toggleMuted;
    private syncMutedState;
    private syncMuteControlVisibility;
    private bindMediaStateEvents;
    private clearMediaStateEvents;
    private isVideoMuted;
    private togglePause;
    private syncPausedState;
    private supportsHoverPauseControl;
    private showPauseControlElement;
    private hidePauseControl;
    private syncPauseControlIcon;
    private syncIconVisibility;
    private getPauseIcon;
    private getPlayIcon;
    private getControlFromEvent;
    private getPointTargetFromEvent;
    private isPointerInsideStoryRect;
    private isPointInsideOptionalRect;
    private isPointInsideRect;
    private isPointerInsideStoryControlArea;
    private isStoryHoverBlockedByControl;
    private showTouchControlsTemporarily;
    private scheduleTouchControlsHide;
    private clearMobileControlsTimer;
    private isInteractiveStoryControlTarget;
    private getStoriesTrack;
    private getRemainingTime;
    private getPausedTimerState;
    private getStoryCount;
    private getSafeStoryIndex;
    private getStoryVideos;
    private getPlayableStoryVideo;
    private syncMultipleVideoControls;
    private warnMultipleVideos;
    private getCurrentVideo;
    private pauseCurrentVideo;
    private playCurrentVideo;
    private pauseAllVideos;
    private hasVideos;
    private hasVideoAudio;
    private clearStoryTimeout;
    private clearTimer;
    private resetProgress;
    private clearTriggers;
    private destroyControls;
    private clearControlEvents;
    private unbindTrackHoverEvents;
    private destroyProgress;
    private removeCreatedElement;
    private destroyEdgeSwipeLock;
    private createProgressContainer;
    private createProgressBars;
    private getProgressItemTemplate;
    private createProgressItem;
    private cloneProgressItem;
    private prepareProgressItem;
    private createPauseControl;
    private createMuteControl;
    private createControlButton;
    private prepareControlButton;
    private getStoriesElement;
    private getTriggerElements;
    private resolveOptions;
    private resolveDuration;
    private resolveMaxVideoDuration;
    private resolveMaxStories;
}
export { BrickSliderStories as BSStoriesPlugin };
