import { Plugin } from '@sixsrc/brick-slider/api';
import { BrickSliderAccessibilityOptions } from './types';
export declare class BrickSliderAccessibility extends Plugin {
    private dotCleanupCallbacks;
    private readonly pluginOptions;
    private rootCleanupCallback;
    private slideClassObserver;
    private slideClassFrame;
    private slideMeta;
    private readonly handleMounted;
    private readonly handleSlideChange;
    private readonly handleDestroyed;
    private readonly handleResize;
    constructor(options?: BrickSliderAccessibilityOptions);
    constructor($root: string, options?: BrickSliderAccessibilityOptions);
    init(): void;
    destroy(): void;
    private syncAccessibility;
    private observeSlideClassChanges;
    private hasSlideClassMutation;
    private scheduleSlideClassSync;
    private disconnectSlideClassObserver;
    private syncAccessibilityWithDelay;
    private ensureAccessibilityStyle;
    private createAccessibilityStyleElement;
    private setupRootAccessibility;
    private setupTrackAccessibility;
    private setupArrowAccessibility;
    private setupArrowElementAccessibility;
    private getArrowDirection;
    private getArrowLabel;
    private setArrowControls;
    private setupDotsAccessibility;
    private setupDotsContainerAccessibility;
    private setupDotsElementsAccessibility;
    private setupDotElementAccessibility;
    private createDotKeydownHandler;
    private handleDotKeydown;
    private setDotControls;
    private setDotCurrentAttribute;
    private bindDotKeydown;
    private syncFocusedDot;
    private shouldFocusActiveDot;
    private getActiveDot;
    private syncSlidesAccessibility;
    private isSlideVisibleForAccessibility;
    private setSlideAccessibility;
    private ensureLiveRegion;
    private createLiveRegionElement;
    private removeLiveRegion;
    private updateLiveRegion;
    private getLiveRegionMessage;
    private getVisibleSlidesForLiveRegion;
    private getFirstLiveRegionSlideNumber;
    private getLastLiveRegionSlideNumber;
    private clearDotsAccessibility;
    private setupKeyboardNavigation;
    private createKeyboardNavigationHandler;
    private handleKeyboardNavigation;
    private bindKeyboardNavigation;
    private clearRootAccessibility;
    private getSlideNumber;
    private isSlideVisibleInViewport;
    private getTrackRect;
    private getVisibleSlideWidth;
    private getVisibilityRatio;
    private getRootAriaLabel;
    private getLastPageIndex;
    private getArrowElements;
    private getDotsContainerElement;
    private getDotElements;
    private getLiveRegionElement;
    private isArrowDisabled;
    private getCurrentFocusedDot;
    private getFocusedDotIndex;
    private isValidDotIndex;
    private isCurrentDot;
    private resolveOptions;
}
