import { BaseSlider } from './BaseSlider';
export declare class Arrows extends BaseSlider {
    $root: string;
    private slider;
    private lastTouchArrowTimestamp;
    constructor($root: string);
    init(): void;
    private syncArrowLabels;
    private setArrowLabel;
    private getArrowButtons;
    private bindArrowEvents;
    private handleArrowPointerDown;
    private handleArrowClick;
    private shouldIgnoreSyntheticTouchClick;
    private handleArrowInteraction;
    private getArrowEventType;
    private getExplicitArrowType;
    private matchesArrowClass;
    private getFallbackArrowType;
    private getScopedArrowButtons;
    private getArrowButtonIndex;
    private arrowHandler;
    private applyArrowNavigationState;
    private getArrowSlideMovement;
    private getArrowNavigationState;
    private applyArrowSlideMovementState;
    private applyArrowStartPosState;
    private applyArrowNavigationTargetState;
    private runFreeArrowNavigation;
    private runPagedArrowNavigation;
    private handleFreeArrowNavigation;
    private handlePagedArrowNavigation;
    protected evalSlideConditions(): Record<string, boolean>;
    private startPosState;
}
