import { BaseSlider } from './BaseSlider';
import { SliderOptions, SliderPlugin } from './types';
export declare class BrickSlider extends BaseSlider {
    userOptions?: SliderOptions;
    private mount;
    private plugins;
    private validate;
    private message;
    private readonly initialInnerHTML;
    private readonly initialClassName;
    private readonly initialStyle;
    constructor($root: string, options?: SliderOptions);
    private validation;
    private defineConfigs;
    private setOptions;
    init(): void;
    private hideUntilMounted;
    private runMount;
    private emitMountedWhenReady;
    next(): void;
    prev(): void;
    goTo(index: number): void;
    destroy(): void;
    use(plugin: SliderPlugin): void;
    private canInteract;
    private destroyPlugins;
    private getSlider;
    private getPluginName;
    private isValidPluginType;
    private isMatchingPluginRoot;
    private getInitialInnerHTML;
    private getInitialClassName;
    private getInitialStyle;
    private navigate;
    private getNavigationState;
    private restoreRootElement;
    private restoreRootStyle;
    private resetMountState;
}
