import { BaseSlider } from './BaseSlider';
import { StateType } from './types';
export declare class Dots extends BaseSlider {
    private slider;
    private containerDots;
    slides: HTMLElement[];
    constructor($root: string);
    init(): void;
    private calculateDots;
    private getTotalPages;
    private getActualSlideCount;
    private canCalculateDots;
    private getLoopTotalPages;
    private getPagedTotalPages;
    private getSafeTotalPages;
    private createDots;
    private applyPaginationState;
    private canCreateDots;
    private paginationState;
    private getSafeDotIndex;
    private canRenderDots;
    private getExistingDots;
    private getTemplateDot;
    private renderDots;
    private clearExistingDots;
    private setInitialActiveDot;
    private toggleDotState;
    private activateDot;
    private deactivateDot;
    private dotHandler;
    private numOfSlidesState;
    private eventMount;
    private getDotElements;
    private bindDotEvents;
    private forEachDot;
    private getDotTargetIndex;
    private getRealSlides;
    private getStepSize;
    private getLoopDotTargetIndex;
    private getPagedDotTargetIndex;
    private getPagedPositions;
    private handleClick;
    protected currentEventType(): Partial<StateType>;
    protected slideIndexState(index: number): Partial<StateType>;
    protected numberOfSlidesState(): Partial<StateType>;
}
