import { MouseEventOrTouchEvent, UpdateSlideIndexType } from './types';
export declare const DOM_ELEMENT_ALIASES: {
    readonly TRACK: readonly ["bs-track"];
    readonly CHILDREN: readonly ["bs-container"];
    readonly SLIDE: readonly ["bs-slide"];
    readonly DOTS: readonly ["bs-dots"];
    readonly DOT: readonly ["bs-dot"];
    readonly DOT_ACTIVE: readonly ["bs-dot--active"];
    readonly PAGES: readonly ["bs-pages"];
    readonly PROGRESS: readonly ["bs-progress"];
    readonly PROGRESS_BAR: readonly ["bs-progress-bar"];
    readonly ARROW: readonly ["bs-arrow"];
    readonly ARROW_PREV: readonly ["bs-prev"];
    readonly ARROW_NEXT: readonly ["bs-next"];
    readonly HIDDEN: readonly ["bs-hidden"];
    readonly DESTROYED: readonly ["bs-destroyed"];
};
export declare const CLASS_VALUES: {
    ACTIVE: string;
    SLIDER_DOT: string;
    SELECTED: string;
    CLONED: string;
    HIDE: string;
    START: string;
    END: string;
};
export declare const TAGS: {
    UL: string;
    LI: string;
    BUTTON: string;
    DIV: string;
    SPAN: string;
    STYLE: string;
    VIDEO: string;
};
export declare const FROM: {
    readonly DOTS: "dots";
    readonly RIGHT_CLICK: "contextmenu";
    readonly PREV: "prev";
    readonly NEXT: "next";
    readonly TOUCH: "touch";
    readonly TOUCHEND: "touchend";
};
export declare const ATTRIBUTES: {
    readonly ID: "id";
    readonly TYPE: "type";
    readonly TABINDEX: "tabindex";
    readonly DATA_INDEX: "data-index";
    readonly DATA_NUMBER: "data-slide-number";
    readonly DATA_PROGRESS_SYNCED_AT: "data-progress-synced-at";
    readonly CLASS: "class";
    readonly STYLE: "style";
    readonly ARIA_LABEL: "aria-label";
    readonly ARIA_HIDDEN: "aria-hidden";
    readonly ARIA_LIVE: "aria-live";
    readonly ARIA_ATOMIC: "aria-atomic";
    readonly ARIA_CURRENT: "aria-current";
    readonly ARIA_DISABLED: "aria-disabled";
    readonly ARIA_CONTROLS: "aria-controls";
    readonly ARIA_MODAL: "aria-modal";
    readonly ARIA_ROLEDESCRIPTION: "aria-roledescription";
    readonly ROLE: "role";
    readonly DISABLED: "disabled";
    readonly DRAGGABLE: "draggable";
    readonly ARIA_VALUE_MIN: "aria-valuemin";
    readonly ARIA_VALUE_MAX: "aria-valuemax";
    readonly ARIA_VALUE_NOW: "aria-valuenow";
};
export declare const TIMES: {
    DEFAULT_TRANSITION_TIME: number;
    FAST_TRANSITION_TIME: number;
    MULTI_PAGE_TRANSITION_TIME: number;
    LARGE_PAGE_TRANSITION_TIME: number;
    FAST_MULTI_PAGE_TRANSITION_TIME: number;
    DRAG_FREE_RELEASE_TIME: number;
    FAST_NAVIGATION_OFFSET: number;
    ARROW_NAVIGATION_GUARD: number;
    TOUCH_NAVIGATION_GUARD: number;
    PROGRESS_TRANSITION_TIME: number;
    SWIPE_MOUSE_LEAVE_DELAY: number;
};
export declare const EVENTS: {
    readonly RESIZE: "resize";
    readonly CLICK: "click";
    readonly POINTERDOWN: "pointerdown";
    readonly POINTERUP: "pointerup";
    readonly POINTERCANCEL: "pointercancel";
    readonly KEYDOWN: "keydown";
    readonly TOUCHSTART: "touchstart";
    readonly TOUCHEND: "touchend";
    readonly TOUCHMOVE: "touchmove";
    readonly MOUSEDOWN: "mousedown";
    readonly MOUSEUP: "mouseup";
    readonly MOUSELEAVE: "mouseleave";
    readonly MOUSEENTER: "mouseenter";
    readonly MOUSEMOVE: "mousemove";
    readonly CONTEXTMENU: "contextmenu";
    readonly TRANSITIONSTART: "transitionstart";
    readonly TRANSITIONEND: "transitionend";
    readonly TRANSITIONCANCEL: "transitioncancel";
    readonly DRAGSTART: "dragstart";
    readonly DRAGOVER: "dragover";
    readonly DRAGEND: "dragend";
};
export declare const SLIDER_EVENTS: {
    readonly MOUNTED: "mounted";
    readonly DESTROYED: "destroyed";
    readonly SLIDE_CHANGE: "slideChange";
};
export declare const ANIMATION_OPTIONS: {
    readonly FORWARDS: "forwards";
    readonly LINEAR: "linear";
    readonly EASEOUT: "cubic-bezier(0.25, 0.1, 0.25, 1)";
    readonly DRAG_FREE_EASING: "cubic-bezier(0.22, 1, 0.36, 1)";
};
export declare const RESPONSIVE_BREAKPOINTS: readonly ["xs", "sm", "md", "lg", "xl", "2xl"];
export declare const NORMALIZED_ELEMENT_ROLES: {
    readonly TRACK: "track";
    readonly CHILDREN: "children";
    readonly SLIDE: "slide";
    readonly ARROW: "bs-arrow";
    readonly PAGES: "bs-pages";
};
export declare const INTERNAL_SELECTORS: {
    readonly PLUGIN_ROOT_PLACEHOLDER: "#__brickslider_plugin_root__";
};
export declare const TOUCH_LIMIT = 0;
export declare const MOVE_TO_LIMIT = 3;
export declare const TOUCH_CONFIG: {
    readonly FAST_SWIPE_MAX_MS: 180;
    readonly FAST_VELOCITY_THRESHOLD: 0.35;
    readonly SLOW_LIMIT: 35;
    readonly MAX_LIMIT: 55;
    readonly DRAG_FREE_SETTLE_FACTOR: 0.12;
};
export declare const POSITION: {
    readonly RIGHT: "right";
    readonly LEFT: "left";
};
export declare const DOCS: {
    readonly GET_STARTED: "https://sixsrc.github.io/brickslider/docs/quick-start/";
    readonly BASIC_HTML_DOC: "https://sixsrc.github.io/brickslider/docs/basic-markup/";
};
export declare const BASIC_DOCS: string;
export declare const START_DOCS: string;
export declare const ERROR_IDS: Set<string>;
export declare function addClass(elements: (HTMLElement | Element)[], className: string): void;
export declare function animateElement(element: HTMLElement | HTMLElement[], keyframes: Keyframe[], options: KeyframeAnimationOptions): Animation[];
export declare function appendToParent(parent: HTMLElement | undefined, element: HTMLElement | undefined): HTMLElement | undefined;
export declare function insertBefore(parent: HTMLElement | undefined, element: HTMLElement | undefined, referenceElement: HTMLElement | undefined): HTMLElement | undefined;
export declare function removeElement(element: HTMLElement | Element | null | undefined): void;
export declare function calcNumberOfSlides(useLoop: boolean, slidesPerPage: number, $children: HTMLElement): number;
export declare function createNewElement(tagName: string): HTMLElement;
export declare function getAllElements<T extends Element>(selector: string, parent?: Document | Element): NodeListOf<T>;
export declare function getElement<T extends Element>(selector: string, parent?: Document | Element): T | undefined;
export declare function $(element: string): HTMLElement | undefined;
export declare function getDotsContainer(rootSelector: string): HTMLElement | undefined;
export declare function getProgressContainer(rootSelector: string): HTMLElement | undefined;
export declare function getChildren(rootSelector: string): HTMLElement | undefined;
export declare function getChildrenCount(el: HTMLElement | undefined): number;
export declare function getDotsSelector($root: string): HTMLElement | undefined;
export declare function getPagesContainer(rootSelector: string): HTMLElement | undefined;
export declare function getRootSelector($root: string): HTMLElement | undefined;
export declare function getSliderNodeList($root: string, cloned?: boolean): HTMLElement[];
export declare function getSliderWidth(el: HTMLElement | undefined): number | undefined;
export declare function getTrackChildren(rootSelector: string): HTMLElement | undefined;
export declare function hasClass(el: HTMLElement, className: string): boolean;
export declare function containsElement(parent: HTMLElement | undefined | null, child: Node | null | undefined): boolean;
export declare function closestElement(element: Element | null | undefined, selector: string): HTMLElement | undefined;
export declare function hasAttribute(el: HTMLElement | undefined | null, attribute: string): boolean;
export declare function getAttribute(el: HTMLElement | undefined | null, attribute: string): string | null;
export declare function removeClass(el: HTMLElement, className: string | string[]): void;
export declare function removePart<T extends string | unknown[]>(input: T, start?: number, end?: number): T;
export declare function setAttribute(el: HTMLElement, attribute: string, value: string): void;
export declare function setAttributes(element: HTMLElement, attributes: Record<string, string | number | boolean>): void;
export declare function getEventType(event: MouseEventOrTouchEvent): MouseEvent | Touch;
export declare function isPrimaryInputButton(event: MouseEventOrTouchEvent): boolean;
export declare function getAxisX(event: MouseEventOrTouchEvent): number;
export declare function getSlideMovement(direction: typeof FROM.NEXT | typeof FROM.PREV): UpdateSlideIndexType;
export declare function isValidSelector(string: string): boolean;
export declare function listener(events: string[], target: EventTarget, callback: EventListenerOrEventListenerObject | ((event: any) => void), options?: boolean | AddEventListenerOptions): void;
export declare function removeListener(events: string[], target: EventTarget, callback: EventListenerOrEventListenerObject | ((event: any) => void), options?: boolean | EventListenerOptions): void;
export declare function removeAttribute(el: HTMLElement, attribute: string): void;
export declare function translate3d(x: number): string;
export declare function waitFor(time: number, callback: () => void): void;
