import { KeyframeAnimation } from './types';
import { BaseSlider } from './BaseSlider';
export declare class Mount extends BaseSlider {
    private clonedSlides;
    private resize;
    private clone;
    private mutate;
    private slider;
    private resolvedSlideWidths;
    constructor($root: string);
    init(): void;
    private setProperties;
    normalizeSlidesConfig(): void;
    private getTotalOriginalSlides;
    private getNormalizedSlidesConfig;
    private canUseOriginalSlidesConfig;
    private getMaxSlidesPerPage;
    private slidesPerViewState;
    private cloneSlides;
    private setAttr;
    private appendSlider;
    private setControls;
    protected keyFrames(index: number): KeyframeAnimation[];
    private getDefaultSlideWidth;
    private getSlideWidthFromAvailableWidth;
    private getSlideWidth;
    private getSlidePosition;
    private hasCustomSlideSizes;
    private resolveGroupWidths;
    private getCustomSlideSizeEntries;
    private getCustomSlideSizeScale;
    private getCustomSlideSizeTotal;
    private getMaxCustomSlideSizeBudget;
    private getDefaultSlotPercentage;
    private getFallbackSlideSizePercentage;
    private getFlexibleSlideSizePositions;
    private setResolvedGroupWidths;
    private getGroupPositions;
    private getAvailableWidth;
    private mountState;
    private handleResize;
    private syncSlidesWidthOnResize;
    private getPreservedSlideIndexOnResize;
    private applyResolvedWidthsOnResize;
    private syncTranslateOnResize;
    private syncPaginationOnResize;
    private calcTranslateFromCurrentIndex;
    private setVisibility;
    private setActiveSlides;
    setSlidesWidth(): void;
    private getVisibleSlideIndexes;
    private getVisualActiveCount;
    private endMount;
}
