import { BaseSlider } from './BaseSlider';
export declare class Resize extends BaseSlider {
    private resizeObserver;
    private onResize?;
    private lastObservedWidth;
    private lastObservedViewportWidth;
    private hasWindowListener;
    private resizeFrame;
    constructor($root: string);
    init(onResize?: () => void): void;
    private observe;
    private listenWindowResize;
    private enableWindowListener;
    private bindWindowResize;
    private scheduleWindowResize;
    private hasPendingResizeFrame;
    private cancelResizeFrame;
    private clearResizeFrame;
    private handleSizeChange;
    private applyResponsiveState;
    private getViewportWidth;
    private getResponsiveState;
    private getResponsiveContext;
    private getResponsiveSlideCounts;
    private createResponsiveState;
    private getMatchedResponsiveConfig;
    private getResponsiveSlidesPerView;
    private getResponsiveSlidesPerPage;
    private getResponsiveSlideSizes;
    private getResponsiveSlideIndex;
    private getCurrentResponsiveSlideIndex;
    private getLoopResponsiveSlideIndex;
    private getClosestResponsiveSlideIndex;
    private getValidPositions;
    private getActiveBreakpoint;
    private hasResponsiveConfig;
    private getOrderedBreakpoints;
    private isConfiguredBreakpoint;
    private resolveActiveBreakpoint;
    private clampSlideCount;
}
