import { BaseSlider } from './BaseSlider';
import { NavigationDirection } from './helpers';
import { TypeTargetSlideParams } from './types';
export declare class Slider extends BaseSlider {
    private animation;
    currentIndex: number;
    protected slides: HTMLElement[];
    private validPositions;
    private mutate;
    private observer;
    private slideMeta;
    private static destroyHandlers;
    constructor($root: string);
    static registerDestroyHandler($root: string, callback: () => void): void;
    static unregisterDestroyHandler($root: string): void;
    prepareForNavigation(): boolean;
    private hasMinimumMarkupStructure;
    private hasValidNavigationMarkup;
    private handleFatalMarkup;
    private healSlideClassNames;
    private healSlideMetaState;
    private restoreActiveSlides;
    private computeValidPositions;
    private computeLoopValidPositions;
    private getPositions;
    private nearestPosition;
    private resolveStartIndex;
    updateCurrentIndexFromTranslate(): void;
    calcTranslateForIndex(index: number): number;
    setSlideTarget(params: TypeTargetSlideParams): void;
    goToDotIndex(targetIndex: number): void;
    goToPageIndex(targetIndex: number): void;
    goToFreeDirection(direction: NavigationDirection): void;
    commitFreeTranslate(targetTranslate: number): void;
    normalizeIndex(index: number): number;
    private setIndexBased;
    private getNextPositionIndex;
    private shouldBlockPagedNavigation;
    private canGuardNavigation;
    private isNavigationLocked;
    private lockNavigation;
    private getPrevPositionIndex;
    private getTargetIndexFromInput;
    private mapDotIndexForLoop;
    private getRealSlideDataIndex;
    defineDotIndex(): void;
    private getDotStartIndex;
    private getDotRawStartIndex;
    private getComputedDotIndex;
    private getDotIndexFromPositions;
    private getNearestPreviousDotIndex;
    private getSafeDotIndex;
    private dotIndexState;
    private dotState;
    updateSlider(): void;
    protected updateDOM(): void;
    updateDots($root: string): void;
    nextAction(): void;
    private getLoopJumpAction;
    private runLoopJumpAction;
    private runForwardLoopJump;
    private getForwardLoopCloneIndex;
    private runBackwardLoopJump;
    private completeLoopJump;
    private enableJumpSlide;
    private disableJumpSlide;
    private jumpSlideState;
    private commitCurrentIndex;
    private syncCurrentActiveSlides;
    private canSyncTargetActiveIndexes;
    private getPagedActiveIndexes;
    private resolveIndexFromTranslate;
    private getResolvedIndexFromRemainingTranslate;
    private getSlideWidthWithGap;
    private getSafeSlideIndex;
    private mainState;
    private animationFrame;
    private runDragFreeAnimation;
    private runPagedAnimation;
    private startActiveSlidesSync;
    private stopActiveSlidesSync;
    private syncActiveSlides;
    private getMaxActiveSlides;
    private clampFreeTranslate;
    private getDragFreeOffset;
    private getDragFreeActiveIndexes;
    private emitSlideChange;
    getInitialIndexFromClones(): number;
}
