import { AnimationFrame } from './AnimationFrame';
import { BaseSlider } from './BaseSlider';
import { KeyframeAnimation, MouseEventOrTouchEvent } from './types';
export declare class TouchEnd extends BaseSlider {
    private static readonly TOUCH_MOVE_ACTIONS;
    protected animation: AnimationFrame;
    private slider;
    private moveSlider;
    constructor($root: string);
    init: (event: MouseEventOrTouchEvent) => void;
    private nextAction;
    private shouldBeEqual;
    protected shouldNotBeSwipe(): boolean;
    private evalSwipeConditions;
    private setTargetCondition;
    protected action(): void;
    private mainState;
    private getTouchLimit;
    private hasTouchTiming;
    private isFastSwipe;
    private getFastTouchLimit;
    private getAdaptiveTouchLimit;
    private getTouchSpeedRatio;
    private getTouchThreshold;
    private clampTouchLimit;
    private handleTouchMove;
    private handleDragFreeTouchEnd;
    private applyTouchMoveSetup;
    private setMoveSlider;
    private handleTouchMoveAction;
    private getTouchMoveContext;
    private shouldHandleDragFreeTouchEnd;
    private getTouchMoveAction;
    private runTouchMoveAction;
    private runDragFreeTouchEnd;
    private shouldHandleSwipeNavigation;
    private runSwipeNavigation;
    private applyTouchMovementState;
    private handleDragFreeTouchEndCommit;
    private shouldCommitDragFreeTouchEnd;
    private commitDragFreeTouchEnd;
    private navigateBySwipeDirection;
    private getLoopPreJumpTargetIndex;
    private navigateToLoopPreJumpTarget;
    private getSwipeNavigationState;
    private applySwipeNavigationState;
    private navigateToSwipeTarget;
    private actionsMove;
    private getSwipeDirection;
    private handleSwipeNavigation;
    private handleTouchMoveFallback;
    private shouldCommitTouchMoveFallback;
    private commitTouchMoveFallback;
    protected keyFrames(): KeyframeAnimation[];
    protected getSpeedInteraction(): number;
    private cancelAnimationFrame;
    private goToNextSlide;
    private goToPrevSlide;
    private setPosition;
    private getTouchEndTranslateState;
    private applyTouchEndTranslateState;
    private navigateToTouchEndTarget;
    private getTouchMovementState;
    private applyPrevSlideState;
    private prevSlideState;
    private eventTargetState;
}
