import { SliderOptions } from './types';
export declare class Validation {
    private static readonly FIXED_ORDER;
    private static readonly ALLOWED_BEFORE_TRACK;
    protected readonly $root: string;
    private ids;
    private details;
    private arrElements;
    constructor($root: string);
    private getRoot;
    private getElementClasses;
    private getTrackClasses;
    private normalizeElementRole;
    private hasAliasClass;
    private isTrackElement;
    private getButtonElements;
    private getBeforeTrack;
    private areArraysEqual;
    isValid(): boolean;
    sanitizeOptions(options?: SliderOptions): SliderOptions | undefined;
    private hasAllElements;
    private isInvalidBeforeTrack;
    private hasAllElementsInOrder;
    private hasDuplicateClasses;
    runValidations(options?: SliderOptions): void;
    getIds(): string[];
    getDetails(id: string): string[];
    private getDuplicateClassNames;
    private getInvalidOrderDetails;
    private isSlideSizesValid;
    private hasUnsupportedSingleViewSlideSizes;
    private hasInvalidSlideSizesValues;
    private sanitizeSlideSizesOptions;
    private sanitizeResponsiveOptions;
    private sanitizeDragFreeOptions;
    private hasDotsWithDragFree;
    private getDotsMarkup;
    private hasResponsiveWithoutScreens;
    private hasInvalidScreenBreakpointKeys;
    private hasInvalidResponsiveBreakpointKeys;
    private hasResponsiveBreakpointsMissingInScreens;
    private getResponsiveBreakpointsMissingInScreens;
    private hasScreenBreakpointValue;
    private isSupportedBreakpoint;
    private isSlideSizesAllowed;
    private isValidSlideSizeEntry;
    protected hasRootContainer(): HTMLElement | undefined;
    protected hasTrackContainer(): HTMLElement | undefined;
    protected hasChildrenContainer(): HTMLElement | undefined;
    protected hasSlide(): HTMLElement | undefined;
}
