name: Publish on tag

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish via Changesets
        uses: changesets/action@v1
        with:
          publish: pnpm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
