name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Release packages via Changesets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release / Publish
        uses: changesets/action@v1
        with:
          publish: pnpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
